#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
BASE=$DIR/..
DOCKER_VERSION=$(node -pe "JSON.parse(process.argv[1])['docker-version']" "$(cat $BASE/package.json)")
DOCKER_MACHINE_VERSION=$(node -pe "JSON.parse(process.argv[1])['docker-machine-version']" "$(cat $BASE/package.json)")
DOCKER_COMPOSE_VERSION=$(node -pe "JSON.parse(process.argv[1])['docker-compose-version']" "$(cat $BASE/package.json)")
CURRENT_DOCKER_VERSION=$($BASE/resources/docker -v | cut -d ',' -f1 | awk '{print $3}' | cut -d '-' -f1)
CURRENT_DOCKER_MACHINE_VERSION=$($BASE/resources/docker-machine -v | cut -d ',' -f1 | awk '{print $3}' | cut -d '-' -f1)
CURRENT_DOCKER_COMPOSE_VERSION=$($BASE/resources/docker-compose --version | cut -d ',' -f1 | awk '{print $2}' | cut -d '-' -f1)
BOOT2DOCKER_FILE=boot2docker-$DOCKER_VERSION.iso

pushd $BASE/resources > /dev/null

if [ "$DOCKER_VERSION" != "$CURRENT_DOCKER_VERSION" ]; then
  echo "-----> Downloading Docker CLI..."
  rm -rf docker
  rm -rf docker-*
  curl -L -o docker-$DOCKER_VERSION.tgz https://get.docker.com/builds/Darwin/x86_64/docker-$DOCKER_VERSION.tgz
  tar xvzf docker-$DOCKER_VERSION.tgz --strip=3
  rm docker-$DOCKER_VERSION.tgz
  chmod +x docker
fi

if [ "$DOCKER_MACHINE_VERSION" != "$CURRENT_DOCKER_MACHINE_VERSION" ]; then
  echo "-----> Downloading Docker Machine CLI..."
  rm -rf docker-machine
  rm -rf docker-machine-*
  curl -L -o docker-machine https://github.com/docker/machine/releases/download/v$DOCKER_MACHINE_VERSION/docker-machine_darwin-amd64
  chmod +x docker-machine
fi

if [ "$DOCKER_COMPOSE_VERSION" != "$CURRENT_DOCKER_COMPOSE_VERSION" ]; then
  echo "-----> Downloading Docker Compose CLI..."
  rm -rf docker-compose
  curl -L -o docker-compose https://github.com/docker/compose/releases/download/$DOCKER_COMPOSE_VERSION/docker-compose-Darwin-x86_64
  chmod +x docker-compose
fi

if [ ! -f $BOOT2DOCKER_FILE ]; then
  echo "-----> Downloading Boot2Docker iso..."
  rm -rf boot2docker-*
  curl -L -o $BOOT2DOCKER_FILE https://github.com/boot2docker/boot2docker/releases/download/v$DOCKER_VERSION/boot2docker.iso
fi


popd > /dev/null
