#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
BASE=$DIR/..
export BOOT2DOCKER_CLI_VERSION=$(node -pe "JSON.parse(process.argv[1])['boot2docker-version']" "$(cat $BASE/package.json)")
export BOOT2DOCKER_CLI_VERSION_FILE=boot2docker-$BOOT2DOCKER_CLI_VERSION

mkdir -p $BASE/cache

pushd $BASE/resources > /dev/null

if [ ! -f $BOOT2DOCKER_CLI_VERSION_FILE ]; then
  echo "-----> Downloading Boot2docker CLI..."
  rm -rf boot2docker-*
  curl -L -o $BOOT2DOCKER_CLI_VERSION_FILE https://github.com/boot2docker/boot2docker-cli/releases/download/v${BOOT2DOCKER_CLI_VERSION}/boot2docker-v${BOOT2DOCKER_CLI_VERSION}-darwin-amd64
  chmod +x $BOOT2DOCKER_CLI_VERSION_FILE
fi

popd > /dev/null
