BASE_IMAGE_VERSION=0.0.1
BASE_IMAGE_VERSION_FILE=base-images-$BASE_IMAGE_VERSION.tar.gz
BASE_IMAGE_FILE=base-images.tar.gz

VIRTUALBOX_FILE=virtualbox-4.3.12.pkg

BOOT2DOCKER_CLI_VERSION=1.1.2
BOOT2DOCKER_CLI_VERSION_FILE=boot2docker-$BOOT2DOCKER_CLI_VERSION
BOOT2DOCKER_CLI_FILE=boot2docker

COCOASUDO_FILE=cocoasudo