#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

rm -rf ~/Library/Application\ Support/Kitematic/
pkill VBox
pkill VirtualBox
$DIR/VirtualBox_Uninstall.tool
rm -rf ~/.boot2docker
rm -rf ~/VirtualBox\ VMs/boot2docker-vm
